# numpy random seed

In [2]:
import pandas as pd 
import numpy as np

# creating arrays

In [21]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [22]:
sample_array1 = np.array([1,2,3,4,5,6,7,8])
sample_array1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
sample_array2 = np.array(4)

In [29]:
sample_array3 = np.array([3,2,1])

In [31]:
sample_array3

array([3, 2, 1])

In [35]:
sample_array3.mean()

2.0

In [37]:
sample_array3.min()

1

In [41]:
sample_array3.dtype

dtype('int32')

In [44]:
ones = np.ones((3,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [46]:
zeros = np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
ones = np.ones_like((3,3))
ones

array([1, 1])

In [50]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [58]:
random_array = np.random.randint(5,10, size=(3,5))
random_array

array([[7, 7, 7, 6, 7],
       [8, 9, 7, 5, 5],
       [5, 9, 7, 7, 7]])

In [59]:
# here random number will keep on changing after every execution

In [77]:
random_array2= np.random.randn(10,3)
random_array2

array([[ 0.62666713,  1.86882528,  0.53447077],
       [ 0.46883333, -0.76673148,  0.18895086],
       [-0.23356028, -1.59221772, -1.78842998],
       [ 0.60490657,  0.99969182, -0.36472278],
       [ 0.53243441,  0.51888896,  1.95156618],
       [-0.2628852 , -1.26186006, -0.08163433],
       [-0.89506287,  0.00498343,  0.32924107],
       [ 0.46724062,  1.06829648,  0.11819988],
       [-1.4134298 , -0.93914445, -0.80260191],
       [-0.53447291, -1.09530648, -0.23359473]])

In [78]:
random_array2.shape

(10, 3)

In [82]:
random_array3 = np.random.random((4,5))
random_array3

array([[0.20468974, 0.24695192, 0.75380315, 0.63688649, 0.6967911 ],
       [0.55587085, 0.4073695 , 0.4837428 , 0.90568242, 0.15817982],
       [0.16625413, 0.19767022, 0.05028805, 0.73273913, 0.98277207],
       [0.35331502, 0.90859067, 0.70675399, 0.77876838, 0.89096148]])

In [105]:
# pseudo-random numbers
np.random.seed(seed=6)

In [113]:
# getting an error \ should be stop generating random numbers

In [108]:
random_array4 = np.random.randint(19, size=(3,5))
random_array4

array([[16,  2,  2, 11,  5],
       [18, 14,  8,  5,  6],
       [10, 10,  3, 11,  1]])

In [112]:
original_data = np.random.exponential(size=5)
original_data

array([1.44711068, 0.33387874, 0.21015599, 0.63724137, 0.40767662])